### ISSUE TITLE
新版本用不了了

### ISSUE THREAD

**Issue by Fawkes-hub** [DogeVenci/utools-recorder#1]
求大佬更新一下

**Comment by DogeVenci** [comment]
utools新版本更新了electron不支持在preload中使用desktopCapturer API
utools也没开放相应API 所以没办法

**Comment by DogeVenci** [comment]
update new API for utools v2.6.3 [69954de](https://github.com/DogeVenci/utools-recorder/commit/69954def61204f7aeca8f869a463040f7ca2c085)
