### ISSUE TITLE
录屏结束后转换mp4失败

### ISSUE THREAD

**Issue by molakirlee** [DogeVenci/utools-recorder#4]
win10系统，采用utool启动，可以正常录屏，录屏结果可以正常播放，但自动转换每次都失败，请问如何解决呢？

**Comment by DogeVenci** [comment]
> win10系统，采用utool启动，可以正常录屏，录屏结果可以正常播放，但自动转换每次都失败，请问如何解决呢？

视频保存目录换到非c盘试试

**Comment by molakirlee** [comment]
谢谢，经指导后，测试发现如下：我的“桌面”之前迁移到了D盘，保存到“桌面”不行，但在D盘新建一个文件夹保存进去的话就可以转换。供您参考。再次感谢解答！

----- 原始邮件 -----
发件人："Doge.Venci" ***@***.***>
收件人：DogeVenci/utools-recorder ***@***.***>
抄送人：molakirlee ***@***.***>,  Author ***@***.***>
主题：Re:_[DogeVenci/utools-recorder]_录屏结束后转换mp4失败_(Issue_#4)
日期：2022年12月01日 15点58分





win10系统，采用utool启动，可以正常录屏，录屏结果可以正常播放，但自动转换每次都失败，请问如何解决呢？



视频保存目录换到非c盘试试
